export const RANDOM_SET = {
  id: 0,
  name: "Random mix",
  utensils: [
    { title: "????????" },
    { title: "????????" },
    { title: "????????" },
    { title: "????????" },
    { title: "????????" },
    { title: "????????" },
    { title: "????????" },
    { title: "????????" },
    { title: "????????" },
    { title: "????????" },
  ],
};

export const STARTER_SETS = [
  {
    id: 1,
    name: "Ice cream flavors",
    utensils: [
      { title: "Vanilla" },
      { title: "Chocolate" },
      { title: "Strawberry" },
      { title: "Mint chocolate chip" },
      { title: "Cookies and cream" },
      { title: "Rocky road" },
      { title: "Butter pecan" },
      { title: "Pistachio" },
      { title: "Cookie dough" },
      { title: "Birthday cake" },
      { title: "Coffee" },
      { title: "Cotton candy" },
      { title: "Dulce de leche" },
      { title: "Bubblegum" },
      { title: "Neapolitan" },
    ],
  },
  {
    id: 2,
    name: "Highest-grossing films",
    utensils: [
      { title: "Gone with the Wind" },
      { title: "Avatar" },
      { title: "Titanic" },
      { title: "Star Wars: A New Hope" },
      { title: "Avengers: Endgame" },
      { title: "The Sound of Music" },
      { title: "E.T." },
      { title: "The Ten Commandments" },
      { title: "Doctor Zhivago" },
      { title: "Star Wars: The Force Awakens" },
    ],
  },
  {
    id: 3,
    name: "Popular versions of Monopoly",
    utensils: [
      { title: "Classic Monopoly" },
      { title: "Monopoly Junior" },
      { title: "Monopoly Mega Edition" },
      { title: "Monopoly Electronic Banking" },
      { title: "Monopoly Deal (Card Game)" },
      { title: "Monopoly Cheaters Edition" },
      { title: "Monopoly Here & Now" },
      { title: "Monopoly Speed" },
      { title: "Monopoly Empire" },
      { title: "Monopoly Millionaire" },
    ],
  },
  {
    id: 4,
    name: "Common dog breeds",
    utensils: [
      { title: "Labrador Retriever" },
      { title: "German Shepherd" },
      { title: "Golden Retriever" },
      { title: "Bulldog" },
      { title: "Poodle" },
      { title: "Beagle" },
      { title: "Rottweiler" },
      { title: "Yorkshire Terrier" },
      { title: "Dachshund" },
      { title: "Boxer" },
      { title: "Siberian Husky" },
      { title: "Shih Tzu" },
      { title: "Doberman Pinscher" },
      { title: "Chihuahua" },
      { title: "Australian Shepherd" },
    ],
  },
  {
    id: 5,
    name: "Aquatic animals",
    utensils: [
      { title: "Dolphin" },
      { title: "Shark" },
      { title: "Whale" },
      { title: "Octopus" },
      { title: "Jellyfish" },
      { title: "Sea turtle" },
      { title: "Clownfish" },
      { title: "Starfish" },
      { title: "Seal" },
      { title: "Manatee" },
      { title: "Squid" },
      { title: "Manta ray" },
    ],
  },
  {
    id: 6,
    name: "Face emojis",
    utensils: [
      { title: "😊" },
      { title: "😂" },
      { title: "😍" },
      { title: "🥺" },
      { title: "🥳" },
      { title: "🤔" },
      { title: "😅" },
      { title: "😜" },
      { title: "😢" },
      { title: "😎" },
      { title: "😴" },
      { title: "🤩" },
      { title: "🥴" },
      { title: "😳" },
      { title: "😌" },
      { title: "😇" },
      { title: "😈" },
      { title: "😤" },
      { title: "😵" },
      { title: "🤯" },
    ],
  },
  {
    id: 7,
    name: "Seven Wonders of the Ancient World",
    utensils: [
      { title: "Great Pyramid of Giza" },
      { title: "Hanging Gardens of Babylon" },
      { title: "Statue of Zeus at Olympia" },
      { title: "Temple of Artemis" },
      { title: "Mausoleum at Halicarnassus" },
      { title: "Colossus of Rhodes" },
      { title: "Lighthouse of Alexandria" },
    ],
  },
  {
    id: 8,
    name: "Popular vacation spots",
    utensils: [
      { title: "Paris, France" },
      { title: "Bali, Indonesia" },
      { title: "Kyoto, Japan" },
      { title: "Rome, Italy" },
      { title: "Maui, Hawaii, US" },
      { title: "Santorini, Greece" },
      { title: "Dubai, UAE" },
      { title: "Sydney, Australia" },
    ],
  },
  {
    id: 9,
    name: "Harry Potter books",
    utensils: [
      { title: "Sorcerer's Stone" },
      { title: "Chamber of Secrets" },
      { title: "Prisoner of Azkaban" },
      { title: "Goblet of Fire" },
      { title: "Order of the Phoenix" },
      { title: "Half-Blood Prince" },
      { title: "Deathly Hallows" },
    ],
  },
  {
    id: 10,
    name: "Summer Olympic sports",
    utensils: [
      { title: "Archery" },
      { title: "Badminton" },
      { title: "Equestrian" },
      { title: "Fencing" },
      { title: "Golf" },
      { title: "Handball" },
      { title: "Rowing" },
      { title: "Skateboarding" },
      { title: "Swimming" },
      { title: "Table tennis" },
      { title: "Volleyball" },
      { title: "Wrestling" },
    ],
  },
  {
    id: 11,
    name: "Best-selling video games",
    utensils: [
      { title: "Minecraft" },
      { title: "Grand Theft Auto V" },
      { title: "Wii Sports" },
      { title: "Mario Kart 8" },
      { title: "PUBG: Battlegrounds" },
      { title: "Red Dead Redemption 2" },
      { title: "Terraria" },
      { title: "Super Mario Bros." },
      { title: "Human: Fall Flat" },
      { title: "The Witcher 3: Wild Hunt" },
    ],
  },
  {
    id: 12,
    name: "Popular Disney movies",
    utensils: [
      { title: "The Lion King" },
      { title: "Aladdin" },
      { title: "Beauty and the Beast" },
      { title: "Frozen" },
      { title: "Moana" },
      { title: "Cinderella" },
      { title: "The Little Mermaid" },
      { title: "Sleeping Beauty" },
      { title: "Snow White and the Seven Dwarfs" },
      { title: "Mulan" },
      { title: "Peter Pan" },
      { title: "Tangled" },
      { title: "Pocahontas" },
      { title: "The Jungle Book" },
      { title: "Zootopia" },
      { title: "Toy Story" },
      { title: "Up" },
    ],
  },
  {
    id: 13,
    name: "Popular fast food chains",
    utensils: [
      { title: "McDonald's" },
      { title: "Burger King" },
      { title: "Taco Bell" },
      { title: "KFC" },
      { title: "Wendy's" },
      { title: "Subway" },
      { title: "Chick-fil-A" },
      { title: "Domino's" },
      { title: "Popeyes" },
    ],
  },
  {
    id: 14,
    name: "Popular works of art by Leonardo da Vinci",
    utensils: [
      { title: "The Last Supper" },
      { title: "Mona Lisa" },
      { title: "Vitruvian Man" },
      { title: "The Virgin of the Rocks" },
      { title: "Lady with an Ermine" },
      { title: "Saint John the Baptist" },
    ],
  },
  {
    id: 15,
    name: "Types of lighting fixtures",
    utensils: [
      { title: "Chandelier" },
      { title: "Pendant light" },
      { title: "Recessed light" },
      { title: "Track lighting" },
      { title: "Table lamp" },
      { title: "Floor lamp" },
      { title: "Wall sconce" },
      { title: "Ceiling fan light" },
      { title: "Flush mount light" },
      { title: "Spotlight" },
      { title: "String lights" },
      { title: "LED strip lights" },
    ],
  },
  {
    id: 16,
    name: "String instruments",
    utensils: [
      { title: "Violin" },
      { title: "Viola" },
      { title: "Guitar" },
      { title: "Cello" },
      { title: "Banjo" },
      { title: "Harp" },
      { title: "Mandolin" },
      { title: "Double bass" },
      { title: "Sitar" },
    ],
  },
  {
    id: 17,
    name: "McDonald's menu items",
    utensils: [
      { title: "Big Mac" },
      { title: "Quarter Pounder with Cheese" },
      { title: "McChicken" },
      { title: "Filet-O-Fish" },
      { title: "Cheeseburger" },
      { title: "McFlurry" },
      { title: "Apple Pie" },
      { title: "Hot 'n Spicy McChicken" },
      { title: "McDouble" },
      { title: "Chicken McNuggets" },
      { title: "Egg McMuffin" },
      { title: "Sausage McMuffin" },
    ],
  },
  {
    id: 18,
    name: "Popular cereals",
    utensils: [
      { title: "Frosted Flakes" },
      { title: "Cheerios" },
      { title: "Cinnamon Toast Crunch" },
      { title: "Lucky Charms" },
      { title: "Froot Loops" },
      { title: "Cocoa Puffs" },
      { title: "Honey Bunches of Oats" },
      { title: "Cap'n Crunch" },
      { title: "Raisin Bran" },
      { title: "Rice Krispies" },
      { title: "Trix" },
      { title: "Reese's Puffs" },
      { title: "Apple Jacks" },
      { title: "Corn Flakes" },
      { title: "Special K" },
      { title: "Mini Wheats" },
      { title: "Kix" },
      { title: "Life" },
    ],
  },
  {
    id: 19,
    name: "Types of clouds",
    utensils: [
      { title: "Cumulus" },
      { title: "Stratus" },
      { title: "Cirrus" },
      { title: "Cumulonimbus" },
      { title: "Stratocumulus" },
      { title: "Altocumulus" },
      { title: "Altostratus" },
      { title: "Nimbostratus" },
      { title: "Cirrostratus" },
      { title: "Cirrocumulus" },
    ],
  },
  {
    id: 20,
    name: "Famous optical illusions",
    utensils: [
      { title: "Checker shadow illusion" },
      { title: "Café wall illusion" },
      { title: "Ebbinghaus illusion" },
      { title: "Hermann grid" },
      { title: "Kanizsa triangle" },
      { title: "Müller-Lyer illusion" },
      { title: "Ponzo illusion" },
      { title: "Fraser spiral" },
      { title: "Necker cube" },
      { title: "Lilac chaser" },
      { title: "Spinning dancer" },
      { title: "Troxler's fading" },
      { title: "Impossible trident" },
    ],
  },
  {
    id: 21,
    name: "Minecraft wood types",
    utensils: [
      { title: "Oak" },
      { title: "Spruce" },
      { title: "Birch" },
      { title: "Jungle" },
      { title: "Acacia" },
      { title: "Dark oak" },
      { title: "Mangrove" },
      { title: "Cherry" },
      { title: "Crimson" },
      { title: "Warped" },
    ],
  },
  {
    id: 22,
    name: "Best-selling studio albums",
    utensils: [
      { title: "Thriller (Michael Jackson)" },
      { title: "Back in Black (AC/DC)" },
      { title: "The Dark Side of the Moon (Pink Floyd)" },
      { title: "Hotel California (Eagles)" },
      { title: "Come On Over (Shania Twain)" },
      { title: "Rumours (Fleetwood Mac)" },
      { title: "Bat Out of Hell (Meat Loaf)" },
      { title: "Led Zeppelin IV (Led Zeppelin)" },
      { title: "Bad (Michael Jackson)" },
      { title: "Jagged Little Pill (Alanis Morissette)" },
    ],
  },
  {
    id: 23,
    name: "Ivy League universities",
    utensils: [
      { title: "Brown University" },
      { title: "Columbia University" },
      { title: "Cornell University" },
      { title: "Dartmouth University" },
      { title: "Harvard University" },
      { title: "University of Pennsylvania" },
      { title: "Princeton University" },
      { title: "Yale University" },
    ],
  },
  {
    id: 24,
    name: "Popular sans-serif typefaces",
    utensils: [
      { title: "Arial" },
      { title: "Helvetica" },
      { title: "Poppins" },
      { title: "Futura" },
      { title: "Roboto" },
      { title: "Nunito" },
      { title: "Montserrat" },
      { title: "Open Sans" },
      { title: "Inter" },
    ],
  },
  {
    id: 25,
    name: "Days of the week",
    utensils: [
      { title: "Sunday" },
      { title: "Monday" },
      { title: "Tuesday" },
      { title: "Wednesday" },
      { title: "Thursday" },
      { title: "Friday" },
      { title: "Saturday" },
    ],
  },
  {
    id: 26,
    name: "Months of the year",
    utensils: [
      { title: "January" },
      { title: "February" },
      { title: "March" },
      { title: "April" },
      { title: "May" },
      { title: "June" },
      { title: "July" },
      { title: "August" },
      { title: "September" },
      { title: "October" },
      { title: "November" },
      { title: "December" },
    ],
  },
  {
    id: 27,
    name: "Common types of knots",
    utensils: [
      { title: "Square knot" },
      { title: "Clove hitch" },
      { title: "Bowline" },
      { title: "Double figure eight" },
      { title: "Two half-hitches" },
      { title: "Taut-line hitch" },
      { title: "Fisherman's" },
      { title: "Water knot" },
      { title: "Rolling hitch" },
      { title: "Prusik" },
      { title: "Timber hitch" },
      { title: "Blood knot" },
      { title: "Artillery loop" },
      { title: "Carrick bend" },
      { title: "Sheepshank" },
    ],
  },
  {
    id: 28,
    name: "Types of denim",
    utensils: [
      { title: "Raw" },
      { title: "Selvedge" },
      { title: "Acid-wash" },
      { title: "Stretch" },
      { title: "Crushed" },
      { title: "Bull" },
      { title: "Colored" },
    ],
  },
  {
    id: 29,
    name: "Types of bread",
    utensils: [
      { title: "Sourdough" },
      { title: "Baguette" },
      { title: "Ciabatta" },
      { title: "Brioche" },
      { title: "Rye Bread" },
      { title: "Pumpernickel" },
      { title: "Multigrain" },
      { title: "Whole wheat" },
      { title: "White" },
      { title: "Focaccia" },
      { title: "Challah" },
      { title: "Naan" },
      { title: "Pita" },
      { title: "Flatbread" },
      { title: "Cornbread" },
    ],
  },
  {
    id: 30,
    name: "Types of puppets",
    utensils: [
      { title: "Hand puppet" },
      { title: "Finger puppet" },
      { title: "Marionette" },
      { title: "Shadow puppet" },
      { title: "Ventriloquist puppet" },
      { title: "Sock puppet" },
      { title: "Rod puppet" },
    ],
  },
  {
    id: 31,
    name: "Common figures of speech",
    utensils: [
      { title: "Alliteration" },
      { title: "Circumlocution" },
      { title: "Euphemism" },
      { title: "Hyperbole" },
      { title: "Irony" },
      { title: "Metaphor" },
      { title: "Metonymy" },
      { title: "Onomatopoeia" },
      { title: "Oxymoron" },
      { title: "Personification" },
      { title: "Simile" },
    ],
  },
  {
    id: 32,
    name: "Popular card games",
    utensils: [
      { title: "Poker" },
      { title: "Blackjack" },
      { title: "Solitaire" },
      { title: "Bridge" },
      { title: "Crazy Eights" },
      { title: "Go Fish" },
      { title: "Spoons" },
      { title: "Spades" },
      { title: "Whist" },
    ],
  },
  {
    id: 33,
    name: "Popular web development technologies",
    utensils: [
      { title: "React" },
      { title: "Angular" },
      { title: "Vue" },
      { title: "Svelte" },
      { title: "Solid" },
      { title: "Next.js" },
      { title: "Nuxt.js" },
      { title: "Remix" },
    ],
  },
  {
    id: 34,
    name: "Yoga poses",
    utensils: [
      { title: "Downward dog" },
      { title: "Warrior I" },
      { title: "Warrior II" },
      { title: "Tree pose" },
      { title: "Child's pose" },
      { title: "Cobra pose" },
      { title: "Cat-cow" },
      { title: "Triangle pose" },
      { title: "Seated forward bend" },
      { title: "Bridge pose" },
      { title: "Lotus pose" },
      { title: "Plank pose" },
    ],
  },
  {
    id: 35,
    name: "Wind instruments",
    utensils: [
      { title: "Flute" },
      { title: "Clarinet" },
      { title: "Saxophone" },
      { title: "Oboe" },
      { title: "Bassoon" },
      { title: "Trumpet" },
      { title: "Trombone" },
      { title: "French horn" },
      { title: "Piccolo" },
      { title: "Bass clarinet" },
      { title: "Didgeridoo" },
    ],
  },
  {
    id: 36,
    name: "Common logical fallacies",
    utensils: [
      { title: "Ad hominem" },
      { title: "Strawman" },
      { title: "Appeal to authority" },
      { title: "No true scotsman" },
      { title: "False dilemma" },
      { title: "Slippery slope" },
      { title: "Circular reasoning" },
      { title: "Texas sharpshooter" },
      { title: "Fallacy fallacy" },
      { title: "Bandwagon" },
      { title: "Tu quoque" },
      { title: "Anecdotal" },
      { title: "Burden of proof" },
    ],
  },
  {
    id: 37,
    name: "Popular types of hats",
    utensils: [
      { title: "Fedora" },
      { title: "Beanie" },
      { title: "Baseball cap" },
      { title: "Bowler hat" },
      { title: "Panama hat" },
      { title: "Trilby" },
      { title: "Top hat" },
      { title: "Beret" },
      { title: "Bucket hat" },
      { title: "Sun hat" },
      { title: "Cowboy hat" },
      { title: "Cloche hat" },
    ],
  },
  {
    id: 38,
    name: "Popular skateboarding tricks",
    utensils: [
      { title: "Ollie" },
      { title: "Kickflip" },
      { title: "Heelflip" },
      { title: "Shuvit" },
      { title: "Impossible" },
      { title: "360 flip" },
      { title: "Nollie" },
      { title: "Laser flip" },
    ],
  },
  {
    id: 39,
    name: "Pokémon types",
    utensils: [
      { title: "Normal" },
      { title: "Fire" },
      { title: "Water" },
      { title: "Electric" },
      { title: "Grass" },
      { title: "Ice" },
      { title: "Fighting" },
      { title: "Poison" },
      { title: "Ground" },
      { title: "Flying" },
      { title: "Psychic" },
      { title: "Bug" },
      { title: "Rock" },
      { title: "Ghost" },
      { title: "Dragon" },
      { title: "Dark" },
      { title: "Steel" },
      { title: "Fairy" },
      { title: "Stellar" },
    ],
  },
  {
    id: 40,
    name: "Chess pieces",
    utensils: [
      { title: "King" },
      { title: "Queen" },
      { title: "Rook" },
      { title: "Bishop" },
      { title: "Knight" },
      { title: "Pawn" },
    ],
  },
  {
    id: 41,
    name: "The Twelve Olympians",
    utensils: [
      { title: "Zeus" },
      { title: "Hera" },
      { title: "Poseidon" },
      { title: "Demeter" },
      { title: "Athena" },
      { title: "Apollo" },
      { title: "Artemis" },
      { title: "Ares" },
      { title: "Aphrodite" },
      { title: "Hephaestus" },
      { title: "Hermes" },
      { title: "Dionysus" },
    ],
  },
  {
    id: 42,
    name: "Common types of birds",
    utensils: [
      { title: "Eagle" },
      { title: "Hawk" },
      { title: "Owl" },
      { title: "Falcon" },
      { title: "Parrot" },
      { title: "Crow" },
      { title: "Raven" },
      { title: "Sparrow" },
      { title: "Penguin" },
      { title: "Flamingo" },
      { title: "Peacock" },
      { title: "Hummingbird" },
    ],
  },
  {
    id: 43,
    name: "Noble gases",
    utensils: [
      { title: "Helium" },
      { title: "Neon" },
      { title: "Argon" },
      { title: "Krypton" },
      { title: "Xenon" },
      { title: "Radon" },
      { title: "Oganesson" },
    ],
  },
  {
    id: 44,
    name: "Main characters in SpongeBob SquarePants",
    utensils: [
      { title: "SpongeBob SquarePants" },
      { title: "Patrick Star" },
      { title: "Squidward Tentacles" },
      { title: "Mr. Krabs" },
      { title: "Sandy Cheeks" },
      { title: "Plankton" },
      { title: "Karen" },
      { title: "Mrs. Puff" },
      { title: "Pearl" },
      { title: "Larry the Lobster" },
      { title: "Mermaid Man" },
      { title: "Barnacle Boy" },
    ],
  },
  {
    id: 45,
    name: "Games in Jackbox Party Pack 3",
    utensils: [
      { title: "Guesspionage" },
      { title: "Tee K.O." },
      { title: "Trivia Murder Party" },
      { title: "Quiplash 2" },
      { title: "Fakin' It" },
    ],
  },
  {
    id: 46,
    name: "Playground equipment",
    utensils: [
      { title: "Swings" },
      { title: "Slide" },
      { title: "Monkey bars" },
      { title: "Seesaw" },
      { title: "Sandbox" },
      { title: "Zip line" },
      { title: "Rock wall" },
      { title: "Merry-go-round" },
      { title: "Spring riders" },
    ],
  },
  {
    id: 47,
    name: "Shrek characters",
    utensils: [
      { title: "Shrek" },
      { title: "Donkey" },
      { title: "Princess Fiona" },
      { title: "Lord Farquaad" },
      { title: "Puss in Boots" },
      { title: "Dragon" },
      { title: "Gingerbread Man" },
      { title: "Pinocchio" },
    ],
  },
  {
    id: 48,
    name: "Popular pop tart flavors",
    utensils: [
      { title: "Frosted s'mores" },
      { title: "Frosted cherry" },
      { title: "Frosted blueberry" },
      { title: "Frosted brown sugar cinnamon" },
      { title: "Frosted strawberry" },
      { title: "Frosted chocolate fudge" },
      { title: "Frosted cookies & crème" },
      { title: "Frosted raspberry" },
      { title: "Frosted chocolate chip" },
      { title: "Frosted confetti cupcake" },
    ],
  },
  {
    id: 49,
    name: "Well-known football/soccer players",
    utensils: [
      { title: "Pelé" },
      { title: "Diego Maradona" },
      { title: "Lionel Messi" },
      { title: "Cristiano Ronaldo" },
      { title: "Zinedine Zidane" },
      { title: "Johan Cruyff" },
      { title: "Michel Platini" },
      { title: "Ronaldinho" },
      { title: "Franz Beckenbauer" },
      { title: "Ronaldo Nazário" },
      { title: "David Beckham" },
      { title: "Kylian Mbappé" },
    ],
  },
  {
    id: 50,
    name: "Well-known NFL teams",
    utensils: [
      { title: "Dallas Cowboys" },
      { title: "New England Patriots" },
      { title: "Pittsburgh Steelers" },
      { title: "Green Bay Packers" },
      { title: "San Francisco 49ers" },
      { title: "Chicago Bears" },
      { title: "Miami Dolphins" },
      { title: "New York Giants" },
      { title: "Los Angeles Rams" },
      { title: "Kansas City Chiefs" },
      { title: "Philadelphia Eagles" },
      { title: "Minnesota Vikings" },
      { title: "Buffalo Bills" },
    ],
  },
  {
    id: 51,
    name: "Energy sources",
    utensils: [
      { title: "Solar" },
      { title: "Wind" },
      { title: "Biomass" },
      { title: "Hydropower" },
      { title: "Geothermal" },
      { title: "Nuclear" },
      { title: "Coal" },
      { title: "Natural gas" },
      { title: "Petroleum" },
    ],
  },
  {
    id: 52,
    name: "Among Us maps",
    utensils: [
      { title: "The Skeld" },
      { title: "MIRA HQ" },
      { title: "Polus" },
      { title: "The Airship" },
      { title: "The Fungle" },
    ],
  },
  {
    id: 53,
    name: "Spotify features",
    utensils: [
      { title: "Spotify Wrapped" },
      { title: "DJ" },
      { title: "Smart Shuffle" },
      { title: "Jams" },
      { title: "Blend" },
      { title: "Radio" },
      { title: "Discover Weekly" },
    ],
  },
  {
    id: 54,
    name: "Types of fries",
    utensils: [
      { title: "Standard" },
      { title: "Curly" },
      { title: "Steak" },
      { title: "Waffle" },
      { title: "Tater tots" },
      { title: "Smiley" },
      { title: "Crinkle-cut" },
      { title: "Sweet potato" },
      { title: "Shoestring" },
    ],
  },
  {
    id: 55,
    name: "Crayola crayon color names",
    utensils: [
      { title: "Razzmatazz" },
      { title: "Sunset Orange" },
      { title: "Fuzzy Wuzzy" },
      { title: "Wild Blue Yonder" },
      { title: "Inchworm" },
      { title: "Antique Brass" },
      { title: "Jazzberry Jam" },
      { title: "Purple Mountains' Majesty" },
      { title: "Mango Tango" },
      { title: "Raw Sienna" },
    ],
  },
  {
    id: 56,
    name: "Largest subreddits",
    utensils: [
      { title: "r/funny" },
      { title: "r/AskReddit" },
      { title: "r/gaming" },
      { title: "r/worldnews" },
      { title: "r/todayilearned" },
      { title: "r/Music" },
      { title: "r/aww" },
      { title: "r/movies" },
      { title: "r/memes" },
      { title: "r/science" },
    ],
  },
  {
    id: 57,
    name: "Popular musicals",
    utensils: [
      { title: "The Book of Mormon" },
      { title: "Hamilton" },
      { title: "Rent" },
      { title: "Mamma Mia!" },
      { title: "Hairspray" },
      { title: "In the Heights" },
      { title: "Wicked" },
      { title: "Dear Evan Hansen" },
      { title: "Moulin Rouge!" },
    ],
  },
  {
    id: 58,
    name: "Food mascots",
    utensils: [
      { title: "Keebler Elves" },
      { title: "Colonel Sanders" },
      { title: "Mr. Peanut" },
      { title: "Tony the Tiger" },
      { title: "Kool Aid Man" },
      { title: "Wendy" },
      { title: "Lucky" },
      { title: "Grimace" },
      { title: "Toucan Sam" },
    ],
  },
  {
    id: 59,
    name: "Popular Cartoon Network shows",
    utensils: [
      { title: "The Marvelous Misadventures of Flapjack" },
      { title: "Ed, Edd n Eddy" },
      { title: "Adventure Time" },
      { title: "Steven Universe" },
      { title: "Johnny Bravo" },
      { title: "Powerpuff Girls" },
      { title: "Regular Show" },
      { title: "Courage the Cowardly Dog" },
      { title: "The Amazing World of Gumball" },
      { title: "Chowder" },
      { title: "Dexter's Laboratory" },
      { title: "Johnny Bravo" },
      { title: "Teen Titans" },
      { title: "Foster's Home for Imaginary Friends" },
    ],
  },
  {
    id: 60,
    name: "Colors of the rainbow",
    utensils: [
      { title: "Red" },
      { title: "Orange" },
      { title: "Yellow" },
      { title: "Green" },
      { title: "Blue" },
      { title: "Indigo" },
      { title: "Violet" },
    ],
  },
  {
    id: 61,
    name: "The Beatles albums",
    utensils: [
      { title: "Please Please Me" },
      { title: "With the Beatles" },
      { title: "A Hard Day's Night" },
      { title: "Beatles for Sale" },
      { title: "Help!" },
      { title: "Rubber Soul" },
      { title: "Revolver" },
      { title: "Sgt. Pepper's Lonely Hearts Club Band" },
      { title: "The Beatles" },
      { title: "Yellow Submarine" },
      { title: "Abbey Road" },
      { title: "Let It Be" },
    ],
  },
  {
    id: 62,
    name: "Common sounds",
    utensils: [
      { title: "Cat purr" },
      { title: "Nails on a chalkboard" },
      { title: "Rain" },
      { title: "Snoring" },
      { title: "Car horn" },
      { title: "Ocean waves" },
      { title: "Birds chirping" },
      { title: "Crackling fire" },
      { title: "Food sizzling" },
      { title: "Keyboard tapping" },
      { title: "Clock ticking" },
    ],
  },
  {
    id: 63,
    name: "Characters from The Office",
    utensils: [
      { title: "Michael Scott" },
      { title: "Dwight Schrute" },
      { title: "Jim Halpert" },
      { title: "Pam Beesly" },
      { title: "Ryan Howard" },
      { title: "Andy Bernard" },
      { title: "Robert California" },
      { title: "Stanley Hudson" },
      { title: "Kevin Malone" },
      { title: "Meredith Palmer" },
      { title: "Angela Martin" },
      { title: "Oscar Martinez" },
      { title: "Phyllis Vance" },
      { title: "Roy Anderson" },
      { title: "Jan Levinson" },
      { title: "Kelly Kapoor" },
    ],
  },
  {
    id: 64,
    name: "Formula 1 circuits",
    utensils: [
      { title: "Monza" },
      { title: "Spa-Francorchamps" },
      { title: "Suzuka" },
      { title: "Interlagos" },
      { title: "Silverstone" },
      { title: "Circuit of the Americas" },
      { title: "Red Bull Ring" },
      { title: "Circuit de Monaco" },
      { title: "Circuit Gilles Villeneuve" },
      { title: "Marina Bay Street Circuit" },
      { title: "Circuit de Barcelona-Catalunya" },
    ],
  },
  {
    id: 65,
    name: "Types of coffee drinks",
    utensils: [
      { title: "Black" },
      { title: "Latte" },
      { title: "Cappucino" },
      { title: "Americano" },
      { title: "Espresso" },
      { title: "Doppio" },
      { title: "Cortado" },
      { title: "Flat white" },
      { title: "Mocha" },
      { title: "Macchiato" },
      { title: "Affogato" },
    ],
  },
  {
    id: 66,
    name: "Common pets",
    utensils: [
      { title: "Cat" },
      { title: "Dog" },
      { title: "Parrot" },
      { title: "Fish" },
      { title: "Hamster" },
      { title: "Horse" },
      { title: "Cockatoo" },
    ],
  },
  {
    id: 67,
    name: "Popular programming languages",
    utensils: [
      { title: "JavaScript" },
      { title: "Python" },
      { title: "TypeScript" },
      { title: "Java" },
      { title: "C#" },
      { title: "C++" },
      { title: "C" },
      { title: "PHP" },
      { title: "Go" },
      { title: "Rust" },
      { title: "Assembly" },
      { title: "Swift" },
    ],
  },
  {
    id: 68,
    name: "Popular Christmas songs",
    utensils: [
      { title: "Sleigh Ride" },
      { title: "White Christmas" },
      { title: "All I Want for Christmas Is You" },
      { title: "Jingle Bells" },
      { title: "Grandma Got Run Over by a Reindeer" },
      { title: "Santa Claus Is Comin' to Town" },
      { title: "Feliz Navidad" },
      { title: "O Holy Night" },
      { title: "Wonderful Christmastime" },
      { title: "Winter Wonderland" },
      { title: "It's Beginning to Look a Lot Like Christmas" },
      { title: "Last Christmas" },
    ],
  },
  {
    id: 69,
    name: "Hogwarts houses",
    utensils: [
      { title: "Gryffindor" },
      { title: "Hufflepuff" },
      { title: "Ravenclaw" },
      { title: "Slytherin" },
    ],
  },
  {
    id: 70,
    name: "Knife cuts",
    utensils: [
      { title: "Dice" },
      { title: "Julienne" },
      { title: "Mince" },
      { title: "Chiffonade" },
      { title: "Oblique" },
      { title: "Batonnet" },
      { title: "Brunoise" },
      { title: "Rondelle" },
      { title: "Paysanne" },
    ],
  },
  {
    id: 71,
    name: "Spanish verb conjugations",
    utensils: [
      { title: "Present" },
      { title: "Preterite" },
      { title: "Imperfect" },
      { title: "Conditional" },
      { title: "Future" },
      { title: "Present subjunctive" },
      { title: "Imperfect subjunctive" },
      { title: "Future subjunctive" },
      { title: "Affirmative imperative" },
      { title: "Negative imperative" },
      { title: "Present progressive" },
      { title: "Imperfect progressive" },
      { title: "Conditional progressive" },
      { title: "Future progressive" },
      { title: "Present perfect" },
      { title: "Past perfect" },
      { title: "Preterite perfect" },
      { title: "Future perfect" },
      { title: "Conditional perfect" },
      { title: "Present perfect subjunctive" },
      { title: "Past perfect subjunctive" },
      { title: "Future perfect subjunctive" },
    ],
  },
  {
    id: 72,
    name: "Pizza toppings",
    utensils: [
      { title: "Pepperoni" },
      { title: "Mushrooms" },
      { title: "Onions" },
      { title: "Sausage" },
      { title: "Black olives" },
      { title: "Green peppers" },
      { title: "Pineapple" },
      { title: "Spinach" },
      { title: "Ham" },
      { title: "Bacon" },
      { title: "Anchovies" },
    ],
  },
  {
    id: 73,
    name: "Papa Louie Games",
    utensils: [
      { title: "Papa's Pizzeria" },
      { title: "Papa's Burgeria" },
      { title: "Papa's Taco Mia" },
      { title: "Papa's Freezeria" },
      { title: "Papa's Pancakeria" },
      { title: "Papa's Wingeria" },
      { title: "Papa's Hot Doggeria" },
      { title: "Papa's Cupcakeria" },
      { title: "Papa's Pastaria" },
      { title: "Papa's Donuteria" },
      { title: "Papa's Cheeseria" },
      { title: "Papa's Bakeria" },
      { title: "Papa's Sushiria" },
      { title: "Papa's Scooperia" },
      { title: "Papa's Mocharia" },
      { title: "Papa's Cluckeria" },
      { title: "Papa's Paleteria" },
    ],
  },
  {
    id: 74,
    name: "Doritos flavors",
    utensils: [
      { title: "Cool Ranch" },
      { title: "Nacho Cheese" },
      { title: "Flamas" },
      { title: "Tapatío" },
      { title: "Taco" },
      { title: "Salsa Verde" },
      { title: "Sweet & Tangy BBQ" },
      { title: "Spicy Nacho" },
      { title: "Spicy Sweet Chili" },
      { title: "Golden Sriracha" },
      { title: "Limón" },
      { title: "Blazin' Buffalo & Ranch" },
      { title: "Flamin' Hot Nacho Cheese" },
      { title: "Flamin' Hot Cool Ranch" },
      { title: "Flamin' Hot Limón" },
    ],
  },
  {
    id: 75,
    name: "Leonardo DiCaprio movies",
    utensils: [
      { title: "Titanic" },
      { title: "The Wolf of Wall Street" },
      { title: "Inception" },
      { title: "Shutter Island" },
      { title: "The Revenant" },
      { title: "Catch Me If You Can" },
      { title: "Romeo + Juliet" },
      { title: "The Great Gatsby" },
      { title: "Django" },
      { title: "Once Upon a Time... in Hollywood" },
      { title: "One Battle After Another" },
      { title: "What's Eating Gilbert Grape" },
    ],
  },
  {
    id: 76,
    name: "Songs from Thriller",
    utensils: [
      { title: "Wanna Be Startin' Somethin'" },
      { title: "Baby Be Mine" },
      { title: "The Girl Is Mine" },
      { title: "Thriller" },
      { title: "Beat It" },
      { title: "Billie Jean" },
      { title: "Human Nature" },
      { title: "P.Y.T. (Pretty Young Thing)" },
      { title: "The Lady in My Life" },
    ],
  },
  {
    id: 77,
    name: "Characters from Hamilton",
    utensils: [
      { title: "Aaron Burr" },
      { title: "Alexander Hamilton" },
      { title: "Angelica Schuyler" },
      { title: "Charles Lee" },
      { title: "Elizabeth Schuyler" },
      { title: "George Eacker" },
      { title: "George Washington" },
      { title: "Hercules Mulligan" },
      { title: "James Madison" },
      { title: "James Reynolds" },
      { title: "John Laurens" },
      { title: "King George" },
      { title: "Maria Reynolds" },
      { title: "Marquis de Lafayette" },
      { title: "Peggy Schuyler" },
      { title: "Philip Hamilton" },
      { title: "Samuel Seabury" },
      { title: "Thomas Jefferson" },
    ],
  },
  {
    id: 78,
    name: "Fingers",
    utensils: [
      { title: "Pointer/index finger" },
      { title: "Middle finger" },
      { title: "Ring finger" },
      { title: "Pinky finger" },
      { title: "Thumb" },
    ],
  },
  {
    id: 79,
    name: "Characters from Modern Family",
    utensils: [
      { title: "Claire Dunphy" },
      { title: "Phil Dunphy" },
      { title: "Haley Dunphy" },
      { title: "Alex Dunphy" },
      { title: "Luke Dunphy" },
      { title: "Jay Pritchett" },
      { title: "Gloria Delgado-Pritchett" },
      { title: "Manny Delgado" },
      { title: "Joe Pritchett" },
      { title: "Mitchell Pritchett" },
      { title: "Cameron Tucker" },
      { title: "Lily Tucker-Pritchett" },
    ],
  },
];
